### ISSUE TITLE
segfault when Testing Area

### ISSUE THREAD

**Issue by ghost** [thee-engineer/stargateRL#26]
segfault when Testing Area
```
 batuhan@osmantaskaya  ~  stargateRL                       
[1]    20573 segmentation fault (core dumped)  stargateRL
```

**Comment by thee-engineer** [comment]
This project hasn't been maintained for over a year now. God knows what still works. You can still scavenge parts of it: "procedural generation engine" should work pretty well, and generates nice worlds, "config menu" has some basic GUI to JSON and JSON to GUI conversion. The widget system of the in-game UI was a nice idea and optimised the rendering of things quite a lot. If I get some time one day I will re-write this in one of Go/Python/C(with ASM). If I can help you with any tips, code, on any project you are working on, just shoot an email my way. (this applies to anybody)

**Comment by thee-engineer** [comment]
I', going to close this, check what I said above also look at Issue #27.
